module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      // Allows importing .sql migration files generated by drizzle-kit as strings.
      ['inline-import', { extensions: ['.sql'] }],
    ],
  };
};
